#!/usr/bin/env python3
"""Import a local questionId -> category/driver/subDriver lookup CSV.

Expected CSV columns:
  questionId, category, driver, subDriver
Optional:
  questionText

Rows with blank category/driver/subDriver are skipped by default so the
worksheet generated by audit_manager_question_lookup.py can be filled gradually.
"""
from __future__ import annotations

import argparse
import csv
import os
import re
from pathlib import Path
from typing import Any

from peakon_api.db import get_db


QUESTION_ID_COLUMNS = ("questionId", "question_id", "id", "_id")
SUBDRIVER_COLUMNS = ("subDriver", "subdriver", "sub_driver")


def first_value(row: dict[str, str], names: tuple[str, ...]) -> str:
    for name in names:
        value = row.get(name)
        if value is not None and str(value).strip():
            return str(value).strip()
    return ""


def parse_id(value: str) -> Any:
    try:
        return int(value)
    except Exception:
        return value



def normalize_input_path(path: str) -> str:
    # Git Bash/MSYS can rewrite `/tmp/foo.csv` Docker exec args to
    # `C:/Users/.../Temp/foo.csv`. Inside the Linux container, the file was
    # copied to `/tmp/foo.csv`, so normalize the common drive-letter case.
    if re.match(r"^[A-Za-z]:[\\/]", path):
        return f"/tmp/{os.path.basename(path)}"
    return path

def main() -> None:
    parser = argparse.ArgumentParser(description="Import filled Peakon question lookup CSV into Mongo drivers_catalog.")
    parser.add_argument("csv_path", help="Path to filled CSV inside the container/local environment")
    parser.add_argument("--allow-partial", action="store_true", help="Import rows even if category/driver/subDriver are not all filled")
    args = parser.parse_args()

    path = Path(normalize_input_path(args.csv_path))
    db = get_db()

    seen = 0
    imported = 0
    skipped_blank = 0
    skipped_no_id = 0

    with path.open(newline="", encoding="utf-8-sig") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            seen += 1
            question_id = first_value(row, QUESTION_ID_COLUMNS)
            if not question_id:
                skipped_no_id += 1
                continue

            category = (row.get("category") or "").strip()
            driver = (row.get("driver") or "").strip()
            subdriver = first_value(row, SUBDRIVER_COLUMNS)
            question_text = (row.get("questionText") or row.get("question_text") or "").strip()

            if not args.allow_partial and not (category and driver and subdriver):
                skipped_blank += 1
                continue

            doc: dict[str, Any] = {
                "_id": parse_id(question_id),
                "category": category,
                "driver": driver,
                "subdriver": subdriver,
                "source": "local_question_lookup",
            }
            if question_text:
                doc["questionText"] = question_text

            db.drivers_catalog.update_one({"_id": doc["_id"]}, {"$set": doc}, upsert=True)
            imported += 1

    print(
        {
            "csvPath": str(path),
            "rowsSeen": seen,
            "rowsImported": imported,
            "rowsSkippedBlankLookup": skipped_blank,
            "rowsSkippedNoId": skipped_no_id,
        }
    )


if __name__ == "__main__":
    main()
